version: 0.2

phases: 
  install:
    commands:
      - git clone https://github.com/vegitable/codeceptio-testing-service.git
      - cd codeceptio-testing-service

  pre_build:
    commands:
      - docker-compose up -d --build 

  build:
    commands:
      - docker exec codeceptio-container npm run test:e2eTest
      
  post_build:
    commands:
      - echo "Build has completed."